# Generated by Django 2.1.7 on 2019-04-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190410_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobeil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
